### PR TITLE
Added support for rlwrap

### PR DESCRIPTION
**Pull request by letronje**
Modified liverepl.sh to detect rlwrap and use it when available.

### CODE REVIEW

**Comment by djpowell** [comment]
I'll take a look.  I tend to use liverepl inside emacs via M-x run-lisp, which lets you evaluate expressions in the repl with C-c C-e, so I want to make sure that this doesn't break that.  Of course in emacs, I guess you get most of the rlwrap functionality anyway.

Is liverepl working for you btw?

**Comment by letronje** [comment]
I've tried liverepl on a basic hello world app, it works. Planning to test and use it for a webapp running under tomcat. I'm not an emacs guy yet, hence the rlwrap fix. Let me know if it breaks your emacs experience.

**Comment by kurtharriger** [comment]
I created a revised patch that supports emacs https://github.com/djpowell/liverepl/pull/2.  I would attach it to this issue, but it doesn't seem obvious how to do that on github.

**Comment by djpowell** [comment]
Fixed by https://github.com/djpowell/liverepl/pull/2

**Pull request closed without merging**
